name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build backend
        run: docker build -t decston/backend:latest ./backend

      - name: Build frontend
        run: docker build -t decston/frontend:latest ./frontend

      - name: Push backend
        run: docker push decston/backend:latest

      - name: Push frontend
        run: docker push decston/frontend:latest
