name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Testes Backend
        run: |
          chmod +x ./backend/mvnw
          cd backend
          ./mvnw test

      - name: Teste Frontend
        run: |
          cd frontend
          npm install
          npm run test

      - name: Build backend
        run: docker build -t test-backend ./backend

      - name: Build frontend
        run: docker build -t test-frontend ./frontend
